= Guidelines for repository contributors

私たちのプロジェクトへのコントリビュートに関心を示していただきありがとうございます。 +

本レポジトリは、株式投資に関するデータ・環境を提供し、個人投資家の皆様によるデータ利活用の可能性を検証する、(株)日本取引所グループによる期間限定の実証実験プロジェクトの一環で作成しました。

本レポジトリでは、主にSIGNATE社において開催するコンペティションのサポートをスコープとしており、金融分野に馴染みのない方でも、株価や企業業績の推移などの時系列データを解析し、市場の動向やリスクの分析に取り組めるように執筆されています。


== Our standard

本プロジェクトに関して、問題の報告、建設的な批評、ドキュメントの更新、プルリクエストの要求やパッチの提供、その他の活動を通じて貢献してくれる方に深く感謝いたします。

このプロジェクトに参加する全ての人に対してのハラスメントを禁止します。また、個人攻撃、煽り、公的私的な嫌がらせ、侮辱、その他コントリビュータとして恥ずべき行動を禁止します。

我々は、行動規範に従っていないissue、プルリクエスト等に対して、削除、編集、拒否の権利と責任があります。

== With issues:
我々は、GitHub issuesを参考にコンテンツの改善やバグ修正を行います。

チュートリアルに関してのご要望は、issuesにご意見をいただけますと幸いです。
(投稿の際には、過去に同じ要望がないかご確認ください。)

チュートリアルに関してのご質問は、SIGNATE社のコンペのフォーラムで、タイトル冒頭に[tutorial]とご記載の上、ご質問していただけますと幸いです。

== With pull requests:
本コンペティションの開催中は、チュートリアルの改善、株式分析に資する内容の加筆等をプルリクエストにて受け付けております。
ブランチは、main(release用),develop,feature(加筆修正用)で管理をしております。

なお、プルリクエストを出していただく際には、以下の観点にご注意ください。

- 幅広い読者層に読まれることを想定してください。
- 複数のブランチがありますが、プルリクエストはForkの上、*developブランチ* に対して行ってください。
- 基本的には二つ以上のコミットに分けず、コミットをまとめて行ってください。
- 外部データを使う場合は、著作権等の権利上問題ないことをreadmeで記載してください。
- 文献等を参考にした場合は、下記を参考に参考元を必ず明記してください。

    被引用箇所を「　」で囲い、引用元のタイトルとURLを(タイトル,URL)記載する。
    (具体例)ファンダメンタルズ
    「「経済の基礎的条件」のことで、経済のマクロ面あるいは個別企業の財務状況などのミクロ面についての指標を意味します」
    （JPX用語集,https://www.jpx.co.jp/glossary/ha/530.html）








